
package client.host;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "cardCRUDL", targetNamespace = "http://host/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    client.host.ObjectFactory.class
})
public interface CardCRUDL {


    /**
     * 
     * @return
     *     returns host.ListOfCards
     */
    @WebMethod
    @WebResult(name = "listofcards", partName = "listofcards")
    @Action(input = "http://host/cardCRUDL/showcardsRequest", output = "http://host/cardCRUDL/showcardsResponse")
    public client.host.ListOfCards showcards();

}
